PRAGMA foreign_keys = ON;
CREATE TABLE organizations (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE users (id TEXT PRIMARY KEY, organization_id TEXT REFERENCES organizations(id), name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('OWNER','VIEW_ONLY','STORE_MANAGER','ADMIN')), active INTEGER NOT NULL DEFAULT 1, sms_enabled INTEGER NOT NULL DEFAULT 0, timezone TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE stores (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(id), dunkin_store_number TEXT NOT NULL UNIQUE, name TEXT NOT NULL, address TEXT NOT NULL, city TEXT NOT NULL, state TEXT NOT NULL, postal_code TEXT NOT NULL, phone TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, manager_id TEXT REFERENCES users(id), backup_manager_id TEXT REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE complaints (id TEXT PRIMARY KEY, external_case_id TEXT NOT NULL UNIQUE, store_id TEXT REFERENCES stores(id), assigned_manager_id TEXT REFERENCES users(id), subject TEXT NOT NULL, complaint_text TEXT NOT NULL, category TEXT NOT NULL, severity TEXT NOT NULL, status TEXT NOT NULL, is_ack_overdue INTEGER NOT NULL DEFAULT 0, is_resolution_overdue INTEGER NOT NULL DEFAULT 0, routing_reason TEXT NOT NULL, routing_confidence TEXT NOT NULL, received_at TEXT NOT NULL, dunkin_acknowledged_at TEXT, acknowledgment_body TEXT, manager_notified_at TEXT, manager_acknowledged_at TEXT, investigation_started_at TEXT, resolution_submitted_at TEXT, closed_at TEXT, closed_by TEXT, ack_deadline TEXT NOT NULL, resolution_deadline TEXT, manager_findings TEXT, customer_contacted INTEGER, customer_contact_outcome TEXT, corrective_action TEXT, resolution_notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE complaint_events (id TEXT PRIMARY KEY, complaint_id TEXT NOT NULL REFERENCES complaints(id), event_type TEXT NOT NULL, actor TEXT NOT NULL, timestamp TEXT NOT NULL, metadata TEXT);
CREATE TABLE notifications (id TEXT PRIMARY KEY, complaint_id TEXT REFERENCES complaints(id), event_type TEXT NOT NULL, recipient_user_id TEXT NOT NULL REFERENCES users(id), channel TEXT NOT NULL, message TEXT NOT NULL, status TEXT NOT NULL, provider TEXT NOT NULL, provider_message_id TEXT, created_at TEXT NOT NULL, sent_at TEXT, delivered_at TEXT, failed_at TEXT, failure_reason TEXT);
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX complaint_store_idx ON complaints(store_id); CREATE INDEX complaint_status_idx ON complaints(status); CREATE INDEX event_complaint_idx ON complaint_events(complaint_id); CREATE INDEX notification_complaint_idx ON notifications(complaint_id);
INSERT INTO settings VALUES ('notification_mode','MOCK',datetime('now')),('external_notifications_enabled','false',datetime('now'));

